name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Building Project
        run: python setup.py sdist

      - name: Publish Package and create Tag and Releases
        uses: Commandcracker/pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
